# Generated by Django 4.2.30 on 2026-05-18 03:58

import api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado de Reserva',
                'verbose_name_plural': 'Estados de Reserva',
                'db_table': 'estado_reserva',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'db_table': 'recurso',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('limite_maximo_reservas', models.IntegerField(help_text='Máximo de reservas simultáneas permitidas para este tipo.', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Tipo de Recurso',
                'verbose_name_plural': 'Tipos de Recurso',
                'db_table': 'tipo_recurso',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='api.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reservacion', models.CharField(default=api.models._generar_codigo_unico, editable=False, max_length=20, unique=True)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.ForeignKey(db_column='id_estado_reserva', on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='api.estadoreserva')),
                ('recurso', models.ForeignKey(db_column='id_recurso', on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='api.recurso')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='api.usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
        migrations.AddField(
            model_name='recurso',
            name='tipo_recurso',
            field=models.ForeignKey(db_column='id_tipo_recurso', on_delete=django.db.models.deletion.RESTRICT, related_name='recursos', to='api.tiporecurso'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='ubicacion',
            field=models.ForeignKey(db_column='id_ubicacion', on_delete=django.db.models.deletion.RESTRICT, related_name='recursos', to='api.ubicacion'),
        ),
        migrations.CreateModel(
            name='HistorialReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_anterior', models.ForeignKey(db_column='id_estado_anterior', on_delete=django.db.models.deletion.RESTRICT, related_name='historial_anterior', to='api.estadoreserva')),
                ('estado_nuevo', models.ForeignKey(db_column='id_estado_nuevo', on_delete=django.db.models.deletion.RESTRICT, related_name='historial_nuevo', to='api.estadoreserva')),
                ('reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.RESTRICT, related_name='historial', to='api.reserva')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, related_name='historial_cambios', to='api.usuario')),
            ],
            options={
                'verbose_name': 'Historial de Reserva',
                'verbose_name_plural': 'Historial de Reservas',
                'db_table': 'historial_reserva',
            },
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['usuario'], name='idx_reserva_usuario'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['recurso'], name='idx_reserva_recurso'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_reserva'], name='idx_reserva_fecha'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='idx_reserva_estado'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['codigo_reservacion'], name='idx_reserva_codigo'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('recurso', 'fecha_reserva', 'hora_inicio', 'hora_fin'), name='uq_reserva_horario'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='chk_horario_valido'),
        ),
        migrations.AddIndex(
            model_name='recurso',
            index=models.Index(fields=['tipo_recurso'], name='idx_recurso_tipo'),
        ),
        migrations.AddIndex(
            model_name='recurso',
            index=models.Index(fields=['ubicacion'], name='idx_recurso_ubicacion'),
        ),
        migrations.AddIndex(
            model_name='recurso',
            index=models.Index(fields=['activo'], name='idx_recurso_activo'),
        ),
        migrations.AddIndex(
            model_name='historialreserva',
            index=models.Index(fields=['reserva'], name='idx_historial_reserva'),
        ),
        migrations.AddIndex(
            model_name='historialreserva',
            index=models.Index(fields=['usuario'], name='idx_historial_usuario'),
        ),
        migrations.AddIndex(
            model_name='historialreserva',
            index=models.Index(fields=['timestamp_cambio'], name='idx_historial_timestamp'),
        ),
    ]
