version: '3.8'

services:
  db:
    image: postgres:15
    container_name: gestor_reservas_db
    restart: always
    environment:
      POSTGRES_DB: gestor_reservas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./database:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
